<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>None</DebugType>
        <DebugSymbols>false</DebugSymbols>
        
        <PublishAot>true</PublishAot>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
        <TrimMode>partial</TrimMode>
        <TrimAnalysisWarnings>false</TrimAnalysisWarnings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
        <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
        <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
        <DebuggerSupport>false</DebuggerSupport>
        <EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization>false</EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization>
        <EventSourceSupport>false</EventSourceSupport>
        <StackTraceSupport>false</StackTraceSupport>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>


        <!-- 减小文件大小 -->
        <IlcOptimizationPreference>Size</IlcOptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
        <IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
        <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CodeExtractTool\CodeExtractTool.csproj" />
    </ItemGroup>
</Project>
